version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      HOST: 0.0.0.0
      POSTGRES_USER: matcha
      POSTGRES_PASSWORD: matcha
      POSTGRES_DB: matcha

  matcha:
    image: matcha
    volumes:
      - .:/go/src/github.com/orenkay/matcha
    entrypoint: go test ./...
    links:
      - postgres
    ports:
      - "3000"
    environment:
      ENVIRONMENT: test
